apiVersion: v1
kind: Service
metadata:
  name: usermanagment_back-service
spec:
  selector:
    app: usermanagment_back-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
